### PR TITLE
Check .css extension firstly.

### PR DESCRIPTION
**Pull request by seth2810**

### CODE REVIEW

**Comment by patrickkettner** [comment]
@seth2810 - what benefit does this provide?

**Comment by seth2810** [comment]
Are you seriously? My commit wait greater than half-year... You can close it, because now it's not be relevant for me.

**Comment by patrickkettner** [comment]
Hey @seth2810 
I am really sorry about that. I have never really worked on this project, the original owner mentioned that he didn't have time for it any more so I am trying to do some house cleaning. If I had to guess, your lack of comment on the original pr and any kind of ping or update resulted in it following through the cracks. I am really sorry about that, no disrespect was meant by this. Its just the result of well intentioned people not having enough hours in the day.

I am sure there was a good reason for the PR in the first place, and am therefore sure that others would benefit from it. I would prefer to land it, so that others will be able to enjoy its benefits, but wanted to understand its purpose before taking it on.

If you really do think it should be closed, you can do so, but if you would be able to explain why you felt it would be a good addition way back when you created the PR, that would be great.

thank you

**Comment by seth2810** [comment]
Ok, i'll try to find where it was be useful. Sorry for hitting.

**Pull request closed without merging**
