### PR TITLE
added crossplatform postinstall script

### PR DESCRIPTION
**Pull request by alexan**
Made post install script in node. to make it cross platform compliant 
https://github.com/Modernizr/grunt-modernizr/issues/125

### CODE REVIEW

**Comment by bryce-gibson** [comment]
Personally, I think this is a great idea :-)

We're having issues with the `[[` because our /bin/sh is not bash...

Unfortunately (for us...) we're still using node 0.10, which means this wouldn't work for us due to the lack of execSync...

Maybe something like:
```
var execSync;
try {
  execSync = require('child_process').execSync;
} catch() {
  execSync = require('sync-exec');
}
```
could be an option?

Or, as another thought, [ShellJs](https://github.com/shelljs/shelljs) is another option for these types of tasks.

(ps, should `node npm install --production` change to just `npm install --production`?)

**Comment by alexan** [comment]
modified due to feedback

**Comment by prisis** [comment]
:+1:

**Comment by iSimonWeb** [comment]
:+1:

**Comment by alexan** [comment]
will you merge this changes in the near future? What could be improved?

**Comment by patrickkettner** [comment]
closing ins favor of the already merged #129 - thanks a lot for PR!

**Pull request closed without merging**
